# Generated by Django 3.1.8 on 2021-08-02 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('illustrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='svg',
            name='image',
            field=models.FileField(upload_to='illustrations'),
        ),
    ]
