# Generated by Django 3.1.8 on 2021-08-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('illustrations', '0002_auto_20210802_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='svg',
            name='image',
        ),
        migrations.AddField(
            model_name='svg',
            name='png',
            field=models.FileField(null=True, upload_to='illustrations/png'),
        ),
        migrations.AddField(
            model_name='svg',
            name='svg',
            field=models.FileField(null=True, upload_to='illustrations/svg'),
        ),
        migrations.AlterField(
            model_name='svg',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='svg',
            name='tags',
            field=models.ManyToManyField(null=True, to='illustrations.Tag'),
        ),
    ]
